### ISSUE TITLE
Returning Data from a Dataset

### ISSUE THREAD

**Issue by noorbakerally** [ldp4j/ldp4j#27]
I needed some help regarding a toy application which i'm making using ldp4j, suppose I have a container ParkingContainer handled by ParkingContainerHandler, I want that the members of ParkingContainer to come from a dataset, suppose using a particular SPARQL service, I managed to get the members, how do I insert these members into the resource snapshot so that members can be returned to the client ? In short, how do I manage if my members are coming from somewhere else external to the application ?

thanks

**Comment by mestebangutierrez** [comment]
`What you should do is asynchronously update the container with as many members as you require leveraging Application API, as follows:

1. Get a new session (`org.ldp4j.application.ApplicationContext.createSession()`)
2. Find out the container to which you want to add the members (`org.ldp4j.application.session.ReadSession.find()`)
3. Add the members (`org.ldp4j.application.session.ContainerSnapshot.addMember`)
4. Save the changes in the session (`org.ldp4j.application.session.WriteSession.saveChanges()`)
5. Close the session (`org.ldp4j.application.session.WriteSession.close()`)

Bear in mind that once the changes in a session have been saved/discarded, new changes will not be registered. To carry out other changes a new session should be created. As only one active session is available per thread, in this situation you should close the session before creating a new one.

**Comment by noorbakerally** [comment]
Should this be done inside the get method of the containerhandler ?

**Comment by mestebangutierrez** [comment]
The LDP4j framework will add the members automatically for you, if they have been created in the way I've specified before. However, that procedure cannot be done within a get, because the signature just gives you a ReadSession, and LDP4j should not allow you to create a new session. 

The only data you can return from that get is any other that is not LDP specific, as any LDP specific metadata is handled automagically by the framework.

**Comment by mestebangutierrez** [comment]
Do you have any code I can have a look at?

**Comment by noorbakerally** [comment]
As of now, i just started using ldp4j for a toy app extending the contact application in the eswc tutorial, there is not much really codes but i was trying to do within the get method and like you said, it cannot be done this way,

but if understand from your answer, the framework itself doesn't allow this natively, in some sort, you have to modify the behaviour of generating the container RDF representation, am I right ?

**Comment by mestebangutierrez** [comment]
Not really, because the framework is not meant to be used like that, for the time being. It's purpose is to handle resources, and allow the retrieval of data associated to those resources, which is extended with any metadata required by the LDP specification. And this extension is handled automatically by the framework. 

So when retrieving a container (get operation) you should only focus on the data associated to the container that is not LDP specific (membership is an example of LDP specific stuff). 

The framework allows you to create/update/resources synchronously when handling PUT, POST and DELETE methods (when a handler implementes the appropriate interfaces of the API), or asynchronously following the procedure that I pointed out before.

**Comment by mestebangutierrez** [comment]
I suggest you to have a look at the Framework [application examples module](https://github.com/ldp4j/ldp4j/tree/master/framework/application/examples), in particular to the `DynamicResourceUpdater`, `DynamicResourceResolver`, and `MyApplication` classes.

It is just an example about how things can be updated dynamically in an asynchronous manner. The example only covers a resource update, but the update could be for a container an imply adding members discovered using an SPARQL endpoint behind the scenes...

**Comment by noorbakerally** [comment]
Thanks using your [reply](https://github.com/ldp4j/ldp4j/issues/27#issuecomment-283732667), i was able to add the members dynamically. I did it in the `initialize` method of the `Application` class. I was wondering whether it is possible to also do the same for containers, i.e. creating a container at runtime ?

**Comment by mestebangutierrez** [comment]
Closing as no further activity has been shown in three months.
